---
include:
  - project: shore/ci-templates
    file: templates/pre-commit.yml
  - project: shore/ci-templates
    file: templates/docker.yml
  - project: shore/ci-templates
    file: templates/notify.yml

docker-build:
  extends: .docker-build-shore
  tags: [ns4.shore.co.il]
  except:
    - master

docker-push:
  extends: .docker-push
  tags: [ns4.shore.co.il]
  except:
    - master
